### ISSUE TITLE
Cannot query wirh trailing dot (root)

### ISSUE THREAD

**Issue by JJ1LFC** [wotschofsky/domain-digger#24]
If the search query is something like `example.com` it's OK, but when the query comes with the trailing dot (expressing null zone (root zone) to be a FQDN) like `example.com.` it returns error.
The FQDN should be accepted as it says "It can be everything! An apex, subdomains, or even a URL."

**Comment by wotschofsky** [comment]
Fair point - fixed! Thank you!
