### ISSUE TITLE
Available domains

### ISSUE THREAD

**Issue by eloydegen** [wotschofsky/domain-digger#25]
First, great tool! Thank you.

When querying a domain that is not registered, it says "Registrar unavailable". That is technically correct, however when you want to buy a new domain, that means it is *available* at the registrar. Maybe a different phrasing would be better here. If you disagree, feel free to close the issue, it's just a suggestion.

**Comment by wotschofsky** [comment]
Interesting point. "Unavailable" was intended as the error phrasing as for example [.de domains don't reveal the registar](https://digger.tools/lookup/denic.de/whois).

But what I believe I am really hearing is that you are looking for a reliable indication whether a domain is taken or not - is that correct?

**Comment by wotschofsky** [comment]
I've updated the summary to clearly indicate when a domain isn't registered

**Comment by eloydegen** [comment]
> But what I believe I am really hearing is that you are looking for a reliable indication whether a domain is taken or not - is that correct?

Correct. I looked at your commit, 'not registered' looks more clear. Thanks for the fix!
