### ISSUE TITLE
Ability to sort tables by column

### ISSUE THREAD

**Issue by sir-kokabi** [wotschofsky/domain-digger#28]
For example, sorting subdomains based on the "Still exists" column. It even would also be helpful to filter columns, like showing only the existing subdomains. This feature can be implemented for other tables too.

![image](https://github.com/wotschofsky/domain-digger/assets/116794136/259e77f3-4b5e-47a9-be04-f25472174401)

**Comment by wotschofsky** [comment]
Hey @sir-kokabi, I like the idea of being able to sort columns.

What other tables are there besides certificates, where you would find this useful?

Out of curiosity and to understand you better: What do you use the subdomains finder for?

**Comment by sir-kokabi** [comment]
I'm not an expert in networking, so I don't use this tool the same way a networking specialist would. My primary use of this tool is for Whois lookups and exploring subdomains. For example, I search for GitHub's subdomains to discover additional tools available in other subdomains, such as https://skyline.github.com/, which I found using this approach. Considering this requirements, it's logical for me to view only active subdomains. I'm not interested in domains that begin with an asterisk. Additionally, being able to open links is of high importance to me.

**Comment by wotschofsky** [comment]
Certs and subdomains tables are now sortable
