### ISSUE TITLE
DNS Map not working when self-hosting

### ISSUE THREAD

**Issue by domainbf** [wotschofsky/domain-digger#32]
Hello,
 the DNS Map is invalid, and it says Something went wrong!
Digest: 1862906764

How should it be configured?

**Comment by wotschofsky** [comment]
Are you referring to some results page on https://digger.tools are hosting it yourself?
If the first is true, please send me the exact URL of the page which is failing.

**Comment by domainbf** [comment]
Thank you for your reply.

There is nothing wrong with the digger.tools website

I am self-hosting, DNS Map does not work.

I use vercel hosting.

Web site: https://met.as

**Comment by maaaathis** [comment]
Any error in your Vercel logs?

**Comment by domainbf** [comment]
![IMG_6336](https://github.com/wotschofsky/domain-digger/assets/158622671/e05dfdce-a5f1-4a1d-b163-a84a1f0bf2b0)
![IMG_6337](https://github.com/wotschofsky/domain-digger/assets/158622671/343166d2-ff81-40e5-9bce-5297185c2e8b)
I didn't notice any errors during installation, but in the deployment log, I found this,

**Comment by wotschofsky** [comment]
Did you set up the [`SITE_URL` env variable](https://github.com/wotschofsky/domain-digger/blob/ec5b739e1e5aa35662c287d0e42fafb509c3cd8e/.env.example#L2C1-L2C29)?

**Comment by maaaathis** [comment]
@domainbf 

These logs have nothing to do with the DNS Map page. Take a look at the Function Route: `/lookup/[domain]` - we are looking for `/lookup/[domain]/map` because the error occurred on this page and not as a warning on the normal lookup page.

**Comment by domainbf** [comment]
I did not set up SITE_URL env variable in the installation construction.

**Comment by wotschofsky** [comment]
Then that's probably it :)
Try that and let us know how it goes!

**Comment by domainbf** [comment]
Solved, I set the URL environment variable, redeployed once and it worked, now there is no problem, everything works fine. The problem was with the URL,
Thanks.
