### ISSUE TITLE
Upstash Error max daily request limit exceeded

### ISSUE THREAD

**Issue by domainbf** [wotschofsky/domain-digger#36]
This Edge Function has crashed.

Your connection is working correctly.

Vercel is working correctly.

500: INTERNAL_SERVER_ERROR
Code: EDGE_FUNCTION_INVOCATION_FAILED
ID: sfo1::2rfsm-1719946834090-73c39ce7df95
If you are a visitor, contact the website owner or try again later.

Is there any solution for this situation?

**Comment by maaaathis** [comment]
Any entry in the Vercel error log?

**Comment by domainbf** [comment]
JUL 03 03:40:20.92
GET
---
met.as
/lookup/workspace-wms.bkk-mobil-oil.de/whois
UpstashError: ERR max daily request limit exceeded. Limit: 10000, Usage: 10001. See https://upstash.com/docs/redis/troubleshooting/max_daily_request_limit for details, command was: ["eval","\n local currentKey = KEYS[1] -- identifier including prefixes\n local previousKey = KEYS[2] -- key of the previous bucket\n local tokens = tonumber(ARGV[1]) -- tokens per window\n local now = ARGV[2] -- current timestamp in milliseconds\n local window = ARGV[3] -- interval in milliseconds\n\n local requestsInCurrentWindow = redis.call(\"GET\", currentKey)\n if requestsInCurrentWindow == false then\n requestsInCurrentWindow = 0\n end\n\n local requestsInPreviousWindow = redis.call(\"GET\", previousKey)\n if requestsInPreviousWindow == false then\n requestsInPreviousWindow = 0\n end\n local percentageInCurrent = ( now % window ) / window\n -- weighted requests to consider from the previous window\n requestsInPreviousWindow = math.floor(( 1 - percentageInCurrent ) * requestsInPreviousWindow)\n if requestsInPreviousWindow + requestsInCurrentWindow >= tokens then\n return -1\n end\n\n local newValue = redis.call(\"INCR\", currentKey)\n if newValue == 1 then \n -- The first time this key is set, the value will be 1.\n -- So we only need the expire command once\n redis.call(\"PEXPIRE\", currentKey, window * 2 + 1000) -- Enough time to overlap with a new window + 1 second\n end\n return tokens - ( newValue + requestsInPreviousWindow )\n ",2,"@upstash/ratelimit:lookup-page:47.128.30.229:28665820","@upstash/ratelimit:lookup-page:47.128.30.229:28665819",10,1719949220478,60000] at (node_modules/.pnpm/@upstash+redis@1.28.4/node_modules/@upstash/redis/chunk-WKQU4BBK.mjs:1:1581) at (node_modules/.pnpm/@upstash+redis@1.28.4/node_modules/@upstash/redis/chunk-WKQU4BBK.mjs:1:2803) at (node_modules/.pnpm/@upstash+ratelimit@1.0.1/node_modules/@upstash/ratelimit/dist/index.js:644:0) at (node_modules/.pnpm/@upstash+ratelimit@1.0.1/node_modules/@upstash/ratelimit/dist/index.js:212:0) at (lib/api.ts:19:17) at (middleware.ts:10:2) at (node_modules/.pnpm/next@14.1.3_@babel+core@7.24.0_react-dom@18.2.0_react@18.2.0__react@18.2.0/node_modules/next/dist/esm/server/web/adapter.js:157:0) { name: 'UpstashError' }
JUL 03 03:40:20.42
GET
---
met.as
/lookup/workspace-wms.bkk-mobil-oil.de/whois
[GET] [middleware: "middleware"] /lookup/workspace-wms.bkk-mobil-oil.de/whois reason=EDGE_FUNCTION_INVOCATION_FAILED, status=500, user_error=true
JUL 03 03:39:46.43
GET
---
met.as
/lookup/www.testdrive.eu5.netsuite.com
UpstashError: ERR max daily request limit exceeded. Limit: 10000, Usage: 10001. See https://upstash.com/docs/redis/troubleshooting/max_daily_request_limit for details, command was: ["eval","\n local currentKey = KEYS[1] -- identifier including prefixes\n local previousKey = KEYS[2] -- key of the previous bucket\n local tokens = tonumber(ARGV[1]) -- tokens per window\n local now = ARGV[2] -- current timestamp in milliseconds\n local window = ARGV[3] -- interval in milliseconds\n\n local requestsInCurrentWindow = redis.call(\"GET\", currentKey)\n if requestsInCurrentWindow == false then\n requestsInCurrentWindow = 0\n end\n\n local requestsInPreviousWindow = redis.call(\"GET\", previousKey)\n if requestsInPreviousWindow == false then\n requestsInPreviousWindow = 0\n end\n local percentageInCurrent = ( now % window ) / window\n -- weighted requests to consider from the previous window\n requestsInPreviousWindow = math.floor(( 1 - percentageInCurrent ) * requestsInPreviousWindow)\n if requestsInPreviousWindow + requestsInCurrentWindow >= tokens then\n return -1\n end\n\n local newValue = redis.call(\"INCR\", currentKey)\n if newValue == 1 then \n -- The first time this key is set, the value will be 1.\n -- So we only need the expire command once\n redis.call(\"PEXPIRE\", currentKey, window * 2 + 1000) -- Enough time to overlap with a new window + 1 second\n end\n return tokens - ( newValue + requestsInPreviousWindow )\n ",2,"@upstash/ratelimit:lookup-page:47.128.30.52:28665819","@upstash/ratelimit:lookup-page:47.128.30.52:28665818",10,1719949186079,60000] at (node_modules/.pnpm/@upstash+redis@1.28.4/node_modules/@upstash/redis/chunk-WKQU4BBK.mjs:1:1581) at (node_modules/.pnpm/@upstash+redis@1.28.4/node_modules/@upstash/redis/chunk-WKQU4BBK.mjs:1:2803) at (node_modules/.pnpm/@upstash+ratelimit@1.0.1/node_modules/@upstash/ratelimit/dist/index.js:644:0) at (node_modules/.pnpm/@upstash+ratelimit@1.0.1/node_modules/@upstash/ratelimit/dist/index.js:212:0) at (lib/api.ts:19:17) at (middleware.ts:10:2) at (node_modules/.pnpm/next@14.1.3_@babel+core@7.24.0_react-dom@18.2.0_react@18.2.0__react@18.2.0/node_modules/next/dist/esm/server/web/adapter.js:157:0) { name: 'UpstashError' }
JUL 03 03:39:46.03
GET
---
met.as
/lookup/www.testdrive.eu5.netsuite.com
[GET] [middleware: "middleware"] /lookup/www.testdrive.eu5.netsuite.com reason=EDGE_FUNCTION_INVOCATION_FAILED, status=500, user_error=true
JUL 03 03:39:11.54
GET
---
met.as
/lookup/secure.lumous.io/whois
UpstashError: ERR max daily request limit exceeded. Limit: 10000, Usage: 10001. See https://upstash.com/docs/redis/troubleshooting/max_daily_request_limit for details, command was: ["eval","\n local currentKey = KEYS[1] -- identifier including prefixes\n local previousKey = KEYS[2] -- key of the previous bucket\n local tokens = tonumber(ARGV[1]) -- tokens per window\n local now = ARGV[2] -- current timestamp in milliseconds\n local window = ARGV[3] -- interval in milliseconds\n\n local requestsInCurrentWindow = redis.call(\"GET\", currentKey)\n if requestsInCurrentWindow == false then\n requestsInCurrentWindow = 0\n end\n\n local requestsInPreviousWindow = redis.call(\"GET\", previousKey)\n if requestsInPreviousWindow == false then\n requestsInPreviousWindow = 0\n end\n local percentageInCurrent = ( now % window ) / window\n -- weighted requests to consider from the previous window\n requestsInPreviousWindow = math.floor(( 1 - percentageInCurrent ) * requestsInPreviousWindow)\n if requestsInPreviousWindow + requestsInCurrentWindow >= tokens then\n return -1\n end\n\n local newValue = redis.call(\"INCR\", currentKey)\n if newValue == 1 then \n -- The first time this key is set, the value will be 1.\n -- So we only need the expire command once\n redis.call(\"PEXPIRE\", currentKey, window * 2 + 1000) -- Enough time to overlap with a new window + 1 second\n end\n return tokens - ( newValue + requestsInPreviousWindow )\n ",2,"@upstash/ratelimit:lookup-page:47.128.33.66:28665819","@upstash/ratelimit:lookup-page:47.128.33.66:28665818",10,1719949151268,60000] at (node_modules/.pnpm/@upstash+redis@1.28.4/node_modules/@upstash/redis/chunk-WKQU4BBK.mjs:1:1581) at (node_modules/.pnpm/@upstash+redis@1.28.4/node_modules/@upstash/redis/chunk-WKQU4BBK.mjs:1:2803) at (node_modules/.pnpm/@upstash+ratelimit@1.0.1/node_modules/@upstash/ratelimit/dist/index.js:644:0) at (node_modules/.pnpm/@upstash+ratelimit@1.0.1/node_modules/@upstash/ratelimit/dist/index.js:212:0) at (lib/api.ts:19:17) at (middleware.ts:10:2) at (node_modules/.pnpm/next@14.1.3_@babel+core@7.24.0_react-dom@18.2.0_react@18.2.0__react@18.2.0/node_modules/next/dist/esm/server/web/adapter.js:157:0) { name: 'UpstashError' }
JUL 03 03:39:11.21
GET
---
met.as
/lookup/secure.lumous.io/whois
[GET] [middleware: "middleware"] /lookup/secure.lumous.io/whois reason=EDGE_FUNCTION_INVOCATION_FAILED, status=500, user_error=true
JUL 03 03:38:37.20
GET
---
met.as
/lookup/www.lp.hsbc.com.lb
UpstashError: ERR max daily request limit exceeded. Limit: 10000, Usage: 10001. See https://upstash.com/docs/redis/troubleshooting/max_daily_request_limit for details, command was: ["eval","\n local currentKey = KEYS[1] -- identifier including prefixes\n local previousKey = KEYS[2] -- key of the previous bucket\n local tokens = tonumber(ARGV[1]) -- tokens per window\n local now = ARGV[2] -- current timestamp in milliseconds\n local window = ARGV[3] -- interval in milliseconds\n\n local requestsInCurrentWindow = redis.call(\"GET\", currentKey)\n if requestsInCurrentWindow == false then\n requestsInCurrentWindow = 0\n end\n\n local requestsInPreviousWindow = redis.call(\"GET\", previousKey)\n if requestsInPreviousWindow == false then\n requestsInPreviousWindow = 0\n end\n local percentageInCurrent = ( now % window ) / window\n -- weighted requests to consider from the previous window\n requestsInPreviousWindow = math.floor(( 1 - percentageInCurrent ) * requestsInPreviousWindow)\n if requestsInPreviousWindow + requestsInCurrentWindow >= tokens then\n return -1\n end\n\n local newValue = redis.call(\"INCR\", currentKey)\n if newValue == 1 then \n -- The first time this key is set, the value will be 1.\n -- So we only need the expire command once\n redis.call(\"PEXPIRE\", currentKey, window * 2 + 1000) -- Enough time to overlap with a new window + 1 second\n end\n return tokens - ( newValue + requestsInPreviousWindow )\n ",2,"@upstash/ratelimit:lookup-page:47.128.124.244:28665818","@upstash/ratelimit:lookup-page:47.128.124.244:28665817",10,1719949116769,60000] at (node_modules/.pnpm/@upstash+redis@1.28.4/node_modules/@upstash/redis/chunk-WKQU4BBK.mjs:1:1581) at (node_modules/.pnpm/@upstash+redis@1.28.4/node_modules/@upstash/redis/chunk-WKQU4BBK.mjs:1:2803) at (node_modules/.pnpm/@upstash+ratelimit@1.0.1/node_modules/@upstash/ratelimit/dist/index.js:644:0) at (node_modules/.pnpm/@upstash+ratelimit@1.0.1/node_modules/@upstash/ratelimit/dist/index.js:212:0) at (lib/api.ts:19:17) at (middleware.ts:10:2) at (node_modules/.pnpm/next@14.1.3_@babel+core@7.24.0_react-dom@18.2.0_react@18.2.0__react@18.2.0/node_modules/next/dist/esm/server/web/adapter.js:157:0) { name: 'UpstashError' }
JUL 03 03:38:36.75
GET
---
met.as
/lookup/www.lp.hsbc.com.lb
[GET] [middleware: "middleware"] /lookup/www.lp.hsbc.com.lb reason=EDGE_FUNCTION_INVOCATION_FAILED, status=500, user_error=true
JUL 03 03:38:02.83
GET
---
met.as
/lookup/mxdf.ispgateway.de/certs
UpstashError: ERR max daily request limit exceeded. Limit: 10000, Usage: 10001. See https://upstash.com/docs/redis/troubleshooting/max_daily_request_limit for details, command was: ["eval","\n local currentKey = KEYS[1] -- identifier including prefixes\n local previousKey = KEYS[2] -- key of the previous bucket\n local tokens = tonumber(ARGV[1]) -- tokens per window\n local now = ARGV[2] -- current timestamp in milliseconds\n local window = ARGV[3] -- interval in milliseconds\n\n local requestsInCurrentWindow = redis.call(\"GET\", currentKey)\n if requestsInCurrentWindow == false then\n requestsInCurrentWindow = 0\n end\n\n local requestsInPreviousWindow = redis.call(\"GET\", previousKey)\n if requestsInPreviousWindow == false then\n requestsInPreviousWindow = 0\n end\n local percentageInCurrent = ( now % window ) / window\n -- weighted requests to consider from the previous window\n requestsInPreviousWindow = math.floor(( 1 - percentageInCurrent ) * requestsInPreviousWindow)\n if requestsInPreviousWindow + requestsInCurrentWindow >= tokens then\n return -1\n end\n\n local newValue = redis.call(\"INCR\", currentKey)\n if newValue == 1 then \n -- The first time this key is set, the value will be 1.\n -- So we only need the expire command once\n redis.call(\"PEXPIRE\", currentKey, window * 2 + 1000) -- Enough time to overlap with a new window + 1 second\n end\n return tokens - ( newValue + requestsInPreviousWindow )\n ",2,"@upstash/ratelimit:lookup-page:47.128.54.190:28665818","@upstash/ratelimit:lookup-page:47.128.54.190:28665817",10,1719949082377,60000] at (node_modules/.pnpm/@upstash+redis@1.28.4/node_modules/@upstash/redis/chunk-WKQU4BBK.mjs:1:1581) at (node_modules/.pnpm/@upstash+redis@1.28.4/node_modules/@upstash/redis/chunk-WKQU4BBK.mjs:1:2803) at (node_modules/.pnpm/@upstash+ratelimit@1.0.1/node_modules/@upstash/ratelimit/dist/index.js:644:0) at (node_modules/.pnpm/@upstash+ratelimit@1.0.1/node_modules/@upstash/ratelimit/dist/index.js:212:0) at (lib/api.ts:19:17) at (middleware.ts:10:2) at (node_modules/.pnpm/next@14.1.3_@babel+core@7.24.0_react-dom@18.2.0_react@18.2.0__react@18.2.0/node_modules/next/dist/esm/server/web/adapter.js:157:0) { name: 'UpstashError' }
JUL 03 03:38:02.32
GET
---
met.as
/lookup/mxdf.ispgateway.de/certs
[GET] [middleware: "middleware"] /lookup/mxdf.ispgateway.de/certs reason=EDGE_FUNCTION_INVOCATION_FAILED, status=500, user_error=true
JUL 03 03:37:27.96
GET
---
met.as
/lookup/www.grafana2.dtna.dlthub.telekom.net
UpstashError: ERR max daily request limit exceeded. Limit: 10000, Usage: 10001. See https://upstash.com/docs/redis/troubleshooting/max_daily_request_limit for details, command was: ["eval","\n local currentKey = KEYS[1] -- identifier including prefixes\n local previousKey = KEYS[2] -- key of the previous bucket\n local tokens = tonumber(ARGV[1]) -- tokens per window\n local now = ARGV[2] -- current timestamp in milliseconds\n local window = ARGV[3] -- interval in milliseconds\n\n local requestsInCurrentWindow = redis.call(\"GET\", currentKey)\n if requestsInCurrentWindow == false then\n requestsInCurrentWindow = 0\n end\n\n local requestsInPreviousWindow = redis.call(\"GET\", previousKey)\n if requestsInPreviousWindow == false then\n requestsInPreviousWindow = 0\n end\n local percentageInCurrent = ( now % window ) / window\n -- weighted requests to consider from the previous window\n requestsInPreviousWindow = math.floor(( 1 - percentageInCurrent ) * requestsInPreviousWindow)\n if requestsInPreviousWindow + requestsInCurrentWindow >= tokens then\n return -1\n end\n\n local newValue = redis.call(\"INCR\", currentKey)\n if newValue == 1 then \n -- The first time this key is set, the value will be 1.\n -- So we only need the expire command once\n redis.call(\"PEXPIRE\", currentKey, window * 2 + 1000) -- Enough time to overlap with a new window + 1 second\n end\n return tokens - ( newValue + requestsInPreviousWindow )\n ",2,"@upstash/ratelimit:lookup-page:47.128.46.244:28665817","@upstash/ratelimit:lookup-page:47.128.46.244:28665816",10,1719949047690,60000] at (node_modules/.pnpm/@upstash+redis@1.28.4/node_modules/@upstash/redis/chunk-WKQU4BBK.mjs:1:1581) at (node_modules/.pnpm/@upstash+redis@1.28.4/node_modules/@upstash/redis/chunk-WKQU4BBK.mjs:1:2803) at (node_modules/.pnpm/@upstash+ratelimit@1.0.1/node_modules/@upstash/ratelimit/dist/index.js:644:0) at (node_modules/.pnpm/@upstash+ratelimit@1.0.1/node_modules/@upstash/ratelimit/dist/index.js:212:0) at (lib/api.ts:19:17) at (middleware.ts:10:2) at (node_modules/.pnpm/next@14.1.3_@babel+core@7.24.0_react-dom@18.2.0_react@18.2.0__react@18.2.0/node_modules/next/dist/esm/server/web/adapter.js:157:0) { name: 'UpstashError' }
JUL 03 03:37:27.64
GET
---
met.as
/lookup/www.grafana2.dtna.dlthub.telekom.net
[GET] [middleware: "middleware"] /lookup/www.grafana2.dtna.dlthub.telekom.net reason=EDGE_FUNCTION_INVOCATION_FAILED, status=500, user_error=true
JUL 03 03:36:53.60
GET
---
met.as
/lookup/www.epicudn.answerhub.com
UpstashError: ERR max daily request limit exceeded. Limit: 10000, Usage: 10001. See https://upstash.com/docs/redis/troubleshooting/max_daily_request_limit for details, command was: ["eval","\n local currentKey = KEYS[1] -- identifier including prefixes\n local previousKey = KEYS[2] -- key of the previous bucket\n local tokens = tonumber(ARGV[1]) -- tokens per window\n local now = ARGV[2] -- current timestamp in milliseconds\n local window = ARGV[3] -- interval in milliseconds\n\n local requestsInCurrentWindow = redis.call(\"GET\", currentKey)\n if requestsInCurrentWindow == false then\n requestsInCurrentWindow = 0\n end\n\n local requestsInPreviousWindow = redis.call(\"GET\", previousKey)\n if requestsInPreviousWindow == false then\n requestsInPreviousWindow = 0\n end\n local percentageInCurrent = ( now % window ) / window\n -- weighted requests to consider from the previous window\n requestsInPreviousWindow = math.floor(( 1 - percentageInCurrent ) * requestsInPreviousWindow)\n if requestsInPreviousWindow + requestsInCurrentWindow >= tokens then\n return -1\n end\n\n local newValue = redis.call(\"INCR\", currentKey)\n if newValue == 1 then \n -- The first time this key is set, the value will be 1.\n -- So we only need the expire command once\n redis.call(\"PEXPIRE\", currentKey, window * 2 + 1000) -- Enough time to overlap with a new window + 1 second\n end\n return tokens - ( newValue + requestsInPreviousWindow )\n ",2,"@upstash/ratelimit:lookup-page:47.128.124.31:28665816","@upstash/ratelimit:lookup-page:47.128.124.31:28665815",10,1719949013160,60000] at (node_modules/.pnpm/@upstash+redis@1.28.4/node_modules/@upstash/redis/chunk-WKQU4BBK.mjs:1:1581) at (node_modules/.pnpm/@upstash+redis@1.28.4/node_modules/@upstash/redis/chunk-WKQU4BBK.mjs:1:2803) at (node_modules/.pnpm/@upstash+ratelimit@1.0.1/node_modules/@upstash/ratelimit/dist/index.js:644:0) at (node_modules/.pnpm/@upstash+ratelimit@1.0.1/node_modules/@upstash/ratelimit/dist/index.js:212:0) at (lib/api.ts:19:17) at (middleware.ts:10:2) at (node_modules/.pnpm/next@14.1.3_@babel+core@7.24.0_react-dom@18.2.0_react@18.2.0__react@18.2.0/node_modules/next/dist/esm/server/web/adapter.js:157:0) { name: 'UpstashError' }
JUL 03 03:36:53.10
GET
---
met.as
/lookup/www.epicudn.answerhub.com
[GET] [middleware: "middleware"] /lookup/www.epicudn.answerhub.com reason=EDGE_FUNCTION_INVOCATION_FAILED, status=500, user_error=true
JUL 03 03:36:19.14
GET
---
met.as
/lookup/expe.cardnet.com.do/whois
UpstashError: ERR max daily request limit

I have been refreshing it, but I don’t see any visit records in the website statistics.

**Comment by maaaathis** [comment]
I guess it says everything 😂

`UpstashError: ERR max daily request limit`

**Comment by domainbf** [comment]
Yes, but it's very strange. I checked the umami website statistics and found that there were very few people visiting it, but it exceeded the limit, which is very strange. Therefore, it is necessary to add a query idle time, with an interval of 3 or 5 seconds between each query to prevent robots.

在 2024年7月3日，03:49，mathis ***@***.***> 写道：

﻿

I guess it says everything 😂

UpstashError: ERR max daily request limit

**Comment by maaaathis** [comment]
Yea, that's right. Umami only tracks real visitors who load the tracking code. Visitors (including bots) who do not load your tracking code (due to a tracking blocker or similar) are not included in the statistics.

There are several ways to get rid of these bots. You can set up a middleware, a WAF or even a robots.txt for example.

**Comment by domainbf** [comment]
😃 I mean, the program limits the query time to prevent robots,

**Comment by domainbf** [comment]
![IMG_8660](https://github.com/wotschofsky/domain-digger/assets/158622671/424dcef3-296c-4e93-a55a-6fc06c5118ca)
![IMG_8661](https://github.com/wotschofsky/domain-digger/assets/158622671/3fe66aa0-21cb-4dc2-b8ab-6c9e6cf0a569)
I feel like these are all robots.

**Comment by maaaathis** [comment]
> 😃 I mean, the program limits the query time to prevent robots,

No, the "normal" domain digger doesn't slow down any query's to prevent bots. Only if you have written the code for that.

**Comment by maaaathis** [comment]
> ![IMG_8660](https://github.com/wotschofsky/domain-digger/assets/158622671/424dcef3-296c-4e93-a55a-6fc06c5118ca)
> 
> ![IMG_8661](https://github.com/wotschofsky/domain-digger/assets/158622671/3fe66aa0-21cb-4dc2-b8ab-6c9e6cf0a569)
> 
> I feel like these are all robots.
> 
> 

Yea, these are most likely bots

**Comment by wotschofsky** [comment]
As already mentioned above, this doesn't seem to be an issue with the project but rather a limit set by Upstash.
Their [pricing page](https://upstash.com/pricing) states a 10k/day command limit on the free tier, which is right in line with your screenshots. Therefore, consider moving to their pay-as-you-go tier.

**Comment by wotschofsky** [comment]
Seems to be resolved!
