### ISSUE TITLE
Database quota exception

### ISSUE THREAD

**Issue by domainbf** [wotschofsky/domain-digger#37]
Hello,
I'm sorry to bother you again

Because I don't know why the domain-digger I created always retrieves the domain name automatically, or why someone else called it.

I don't know, because upstash's daily quota of 10000 will be used up in an instant, and then cause the site to crash all day, which has been going on for some time.

I checked the statistics of the website and found that almost no one visited it every day, only I checked it a few times occasionally.

But the upstash quota will be used up soon after the zero is cleared and restarted every day.
![IMG_9167](https://github.com/user-attachments/assets/1e1d6d38-a47a-4ee9-877e-2cc356759133)
![IMG_9168](https://github.com/user-attachments/assets/025caf8f-1f9f-4b2d-9faf-c31ae22a4736)

**Comment by domainbf** [comment]
I tried to delete the database and reinstall it, and more than an hour ago, I created a new database and reinstalled it, but his credit was gone again. The website crashed.
![Uploading IMG_9169.jpeg…]()

**Comment by wotschofsky** [comment]
I believe just like last time, this is a case of having to upgrade to the pay-as-you-go tier on Upstash: https://upstash.com/pricing/redis

Also quick reminder, that this project is [licensed for free under AGPL-3.0](https://choosealicense.com/licenses/agpl-3.0/), so it would be greatly appreciated if you wouldn't constantly go out of your way to remove absolutely every little bit of credit on your instance. :)

**Comment by domainbf** [comment]
I don't know either. I can't see where the problem lies. Logically, the free quota for almost no access should be enough. Regarding the copyright issue, the last icon in the lower right corner is a link to your personal homepage. I will indicate the copyright ownership.
