### ISSUE TITLE
Consider adding additional domain URLs using Hudson Rock Cybercrime Intelligence free integration

### ISSUE THREAD

**Issue by hudsonrock-partnerships** [wotschofsky/domain-digger#40]
Consider adding Hudson Rock's complimentary data to receive additional URLs associated with a specific domain.
The data from machines infected by Infostealer contains URLs that could be not discovered traditionally.

- URLs by Domain sample: https://cavalier.hudsonrock.com/api/json/v2/osint-tools/urls-by-domain?domain=tesla.com

Thank you.

**Comment by wotschofsky** [comment]
Domain Digger is about domains, not URLs
